import './assets/drums/1-snare.mp3';
import './assets/drums/2-bass-drum.mp3';
import './assets/drums/3-side-stick.mp3';
import './assets/drums/4-crash-cymbal.mp3';
import './assets/drums/5-open-hi-hat.mp3';
import './assets/drums/6-closed-hi-hat.mp3';
import './assets/drums/7-tambourine.mp3';
import './assets/drums/8-hand-clap.mp3';
import './assets/drums/9-claves.mp3';
import './assets/drums/10-wood-block.mp3';
import './assets/drums/11-cowbell.mp3';
import './assets/drums/12-triangle.mp3';
import './assets/drums/13-bongo.mp3';
import './assets/drums/14-conga.mp3';
import './assets/drums/15-cabasa.mp3';
import './assets/drums/16-guiro.mp3';
import './assets/drums/17-vibraslap.mp3';
import './assets/drums/18-cuica.mp3';
import './assets/instruments/1-piano/24.mp3';
import './assets/instruments/1-piano/36.mp3';
import './assets/instruments/1-piano/48.mp3';
import './assets/instruments/1-piano/60.mp3';
import './assets/instruments/1-piano/72.mp3';
import './assets/instruments/1-piano/84.mp3';
import './assets/instruments/1-piano/96.mp3';
import './assets/instruments/1-piano/108.mp3';
import './assets/instruments/2-electric-piano/60.mp3';
import './assets/instruments/3-organ/60.mp3';
import './assets/instruments/4-guitar/60.mp3';
import './assets/instruments/5-electric-guitar/60.mp3';
import './assets/instruments/6-bass/36.mp3';
import './assets/instruments/6-bass/48.mp3';
import './assets/instruments/7-pizzicato/60.mp3';
import './assets/instruments/8-cello/36.mp3';
import './assets/instruments/8-cello/48.mp3';
import './assets/instruments/8-cello/60.mp3';
import './assets/instruments/9-trombone/36.mp3';
import './assets/instruments/9-trombone/48.mp3';
import './assets/instruments/9-trombone/60.mp3';
import './assets/instruments/10-clarinet/48.mp3';
import './assets/instruments/10-clarinet/60.mp3';
import './assets/instruments/11-saxophone/36.mp3';
import './assets/instruments/11-saxophone/60.mp3';
import './assets/instruments/11-saxophone/84.mp3';
import './assets/instruments/12-flute/60.mp3';
import './assets/instruments/12-flute/72.mp3';
import './assets/instruments/13-wooden-flute/60.mp3';
import './assets/instruments/13-wooden-flute/72.mp3';
import './assets/instruments/14-bassoon/36.mp3';
import './assets/instruments/14-bassoon/48.mp3';
import './assets/instruments/14-bassoon/60.mp3';
import './assets/instruments/15-choir/48.mp3';
import './assets/instruments/15-choir/60.mp3';
import './assets/instruments/15-choir/72.mp3';
import './assets/instruments/16-vibraphone/60.mp3';
import './assets/instruments/16-vibraphone/72.mp3';
import './assets/instruments/17-music-box/60.mp3';
import './assets/instruments/18-steel-drum/60.mp3';
import './assets/instruments/19-marimba/60.mp3';
import './assets/instruments/20-synth-lead/60.mp3';
import './assets/instruments/21-synth-pad/60.mp3';

export default {
    'drums/1-snare.mp3': null,
    'drums/2-bass-drum.mp3': null,
    'drums/3-side-stick.mp3': null,
    'drums/4-crash-cymbal.mp3': null,
    'drums/5-open-hi-hat.mp3': null,
    'drums/6-closed-hi-hat.mp3': null,
    'drums/7-tambourine.mp3': null,
    'drums/8-hand-clap.mp3': null,
    'drums/9-claves.mp3': null,
    'drums/10-wood-block.mp3': null,
    'drums/11-cowbell.mp3': null,
    'drums/12-triangle.mp3': null,
    'drums/13-bongo.mp3': null,
    'drums/14-conga.mp3': null,
    'drums/15-cabasa.mp3': null,
    'drums/16-guiro.mp3': null,
    'drums/17-vibraslap.mp3': null,
    'drums/18-cuica.mp3': null,
    'instruments/1-piano/24.mp3': null,
    'instruments/1-piano/36.mp3': null,
    'instruments/1-piano/48.mp3': null,
    'instruments/1-piano/60.mp3': null,
    'instruments/1-piano/72.mp3': null,
    'instruments/1-piano/84.mp3': null,
    'instruments/1-piano/96.mp3': null,
    'instruments/1-piano/108.mp3': null,
    'instruments/2-electric-piano/60.mp3': null,
    'instruments/3-organ/60.mp3': null,
    'instruments/4-guitar/60.mp3': null,
    'instruments/5-electric-guitar/60.mp3': null,
    'instruments/6-bass/36.mp3': null,
    'instruments/6-bass/48.mp3': null,
    'instruments/7-pizzicato/60.mp3': null,
    'instruments/8-cello/36.mp3': null,
    'instruments/8-cello/48.mp3': null,
    'instruments/8-cello/60.mp3': null,
    'instruments/9-trombone/36.mp3': null,
    'instruments/9-trombone/48.mp3': null,
    'instruments/9-trombone/60.mp3': null,
    'instruments/10-clarinet/48.mp3': null,
    'instruments/10-clarinet/60.mp3': null,
    'instruments/11-saxophone/36.mp3': null,
    'instruments/11-saxophone/60.mp3': null,
    'instruments/11-saxophone/84.mp3': null,
    'instruments/12-flute/60.mp3': null,
    'instruments/12-flute/72.mp3': null,
    'instruments/13-wooden-flute/60.mp3': null,
    'instruments/13-wooden-flute/72.mp3': null,
    'instruments/14-bassoon/36.mp3': null,
    'instruments/14-bassoon/48.mp3': null,
    'instruments/14-bassoon/60.mp3': null,
    'instruments/15-choir/48.mp3': null,
    'instruments/15-choir/60.mp3': null,
    'instruments/15-choir/72.mp3': null,
    'instruments/16-vibraphone/60.mp3': null,
    'instruments/16-vibraphone/72.mp3': null,
    'instruments/17-music-box/60.mp3': null,
    'instruments/18-steel-drum/60.mp3': null,
    'instruments/19-marimba/60.mp3': null,
    'instruments/20-synth-lead/60.mp3': null,
    'instruments/21-synth-pad/60.mp3': null
};
